version: '2.4'

services:
  notifier:
    build:
      context: .
    image: grocy-notifier:latest
    environment:
      - TZ=America/New_York
      - GROCY_API_KEY=
      - GROCY_URL=
      - WA_GROUP_ID=
      - CRON_CHORE_SCHEDULE=0 0 9 * * *
    volumes:
      - ~/volumes/grocy/notifier:/sessions
